### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by orta** [danger/danger-swift#9]
Swift PM supports test targets, I skipped looking at that so I could get something working.

**Comment by SD10** [comment]
Sorry for the delay on this -- I'm actually having a lot of trouble getting things to run from the test target 😅

**Comment by orta** [comment]
As of #22 tests are now running in linux / mac

**Comment by orta** [comment]
There just aren't any useful ones :D

**Comment by yhkaplan** [comment]
Hey guys, I would like to contribute, but just to confirm, are the tests you're looking for right now mostly about whether your Codable model objects handle JSON encoding/decoding properly? Please tell me if you think I should start somewhere else first.

**Comment by SD10** [comment]
> ...are the tests you're looking for right now mostly about whether your Codable model objects handle JSON encoding/decoding properly?

Hey @yhkaplan, anything to increase test coverage is fine but I think that would be a great place to start! I remember when I started doing this I got caught up trying to find the test resources because I was trying to run the tests via Xcode (which results in a different cwd) and not using `swift test`. Let me know if you have any questions 👍

**Comment by kdawgwilk** [comment]
You might be able to use Swift’s `#file` macro (or whatever it’s called) to get a more consistent directory

**Comment by orta** [comment]
I'm happy with the tests we've got so far 👍 

Going to close this
